### ISSUE TITLE
Memory requirements from creating unused diagonal matrix

### ISSUE THREAD

**Issue by jmerkin** [leeshawn/SKAT#4]
In the function SKAT_Optimal_Logistic_VarMatching, there's a call to create a diagonal matrix that is never used. This matrix is never used but the memory allocation can grow quite large. 

Line 303 in the file SKAT_Optimal_VarMatching.R:
D  = diag(pi_1)

can be removed without seemingly affecting anything downstream.

**Comment by ZhangchenZhao** [comment]
Thanks for this great suggestion! We already remove this line. Please try our updated version, which can be found in "Sparse_Version" branch. Now we can support both matrix and sparse matrix.

**Comment by complexgenome** [comment]
@ZhangchenZhao Hi, sorry to hijack this thread. Can you direct to the "Sparse_Version"? I'd like to use it but unable to find as is the link provided in paper

Robust gene-based test, https://github.com/leeshawn/SKAT/tree/
Sparse_Version  

UK Biobank Whole-Exome Sequence Binary Phenome Analysis with Robust Region-Based Rare-Variant Test
https://www.sciencedirect.com/science/article/pii/S0002929719304331


Thanks.

**Comment by ZhangchenZhao** [comment]
Hi Sanjeev,

Thanks for your email. You can find updated SKAT through this link
https://github.com/leeshawn/SKAT/tree/Sparse_Version. Later this month
we will also upload this SKAT version to CRAN.

Let me know if you have any questions.

Thanks,
Zhangchen
