### ISSUE TITLE
Probably a typo in Binary_MAIN_Robust.R

### ISSUE THREAD

**Issue by abhisheknrl** [leeshawn/SKAT#5]
Hi
I encounter this error when the missing genotype had to be imputed.
`Error in SKATBinary_Robust(Z, obj) : object 'weigths' not found`

Possibly a type?
`Z=Z[,-list_tiny];weights=**weigths**[-list_tiny];`

Thanks!
Abhishek

**Comment by ZhangchenZhao** [comment]
I am sorry about that. We already updated it in the package. Thanks,
