### ISSUE TITLE
Bug in SKATBinary_Robust.SSD.All

### ISSUE THREAD

**Issue by gpovysil** [leeshawn/SKAT#6]
I get the following error when I call SKATBinary_Robust.SSD.All:
Error in OUT.nRare[i] <- re$n.rare : replacement has length zero

re$n.rare and re$n.common are never set because they probably don't belong here but to the CommonRare version of the function.

I'm interested in trying out the new robust version so it would be great if you could fix this.
Thanks in advance.

**Comment by longfei8533** [comment]
I have the same problem.

**Comment by came203** [comment]
Me too

**Comment by came203** [comment]
Just a heads up, I commented out the two lines 

```
OUT.nRare[i]<-re$n.rare
OUT.nCommon[i]<-re$n.common
```
Now it seems to run fine

**Comment by raonyguimaraes** [comment]
Me too!

**Comment by enriquea** [comment]
Hi there,

Any update in this issue? I'm having the same error...

Thanks in advance

**Comment by enriquea** [comment]
> Hi there,
> 
> Any update in this issue? I'm having the same error...
> 
> Thanks in advance

Ok, this is not longer a issue when using the SKAT version 2.2.2 (installed from Github).
```
other attached packages:
[1] SKAT_2.2.2    SPAtest_3.1.2 Matrix_1.2-15
```

**Comment by leeshawn** [comment]
Sorry for not commenting on this. Since it is fixed, I will close this.
